#!/bin/bash

# Script to archive obsolete documentation files
# Created: 2026-01-29

echo "📦 Archiving obsolete documentation files..."
echo ""

# Create archive directory
ARCHIVE_DIR=".archive/obsolete-docs-2026-01-29"
mkdir -p "$ARCHIVE_DIR"

# List of all obsolete files
OBSOLETE_FILES=(
  # Admin Customers
  "ADMIN_CUSTOMERS_AMBIGUOUS_COLUMN_FIX_2026-01-28.md"
  "ADMIN_CUSTOMERS_COLUMN_NAME_FIX_2026-01-28.md"
  "ADMIN_CUSTOMERS_COMPLETE_FIX_SUMMARY_2026-01-28.md"
  "ADMIN_CUSTOMERS_DATA_TYPE_MISMATCH_FIX_2026-01-28.md"
  "ADMIN_CUSTOMERS_DEEP_CLEANUP_COMPLETE_2026-01-28.md"
  "ADMIN_CUSTOMERS_LAST_LOGIN_COLUMN_FIX_2026-01-28.md"
  "ADMIN_CUSTOMERS_LAST_SIGN_IN_AT_REMOVED_2026-01-28.md"
  "ADMIN_CUSTOMERS_MISSING_ROLE_FILTER_FIX_2026-01-28.md"
  "ADMIN_CUSTOMERS_PARAMETER_NAME_FIX_2026-01-28.md"
  "ADMIN_CUSTOMERS_RPC_FIX_2026-01-28.md"
  "ADMIN_CUSTOMERS_SCHEMA_CACHE_RELOAD_2026-01-28.md"
  "ADMIN_CUSTOMERS_UI_REDESIGN_2026-01-28.md"
  "ADMIN_CUSTOMERS_USER_ID_COLUMN_FIX_2026-01-28.md"
  "ADMIN_CUSTOMERS_SUSPENSION_DEBUG_2026-01-28.md"
  "ADMIN_CUSTOMERS_SUSPENSION_COMPLETE_2026-01-28.md"
  
  # Admin Financial Settings
  "ADMIN_FINANCIAL_SETTINGS_ALL_FIXED.md"
  "ADMIN_FINANCIAL_SETTINGS_AUDIT_LOG_FIXED.md"
  "ADMIN_FINANCIAL_SETTINGS_CSS_ARCHITECTURE_ANALYSIS.md"
  "ADMIN_FINANCIAL_SETTINGS_CSS_UX_ANALYSIS.md"
  "ADMIN_FINANCIAL_SETTINGS_DESIGN_COMPLETE.md"
  "ADMIN_FINANCIAL_SETTINGS_EXPORT_FIX.md"
  "ADMIN_FINANCIAL_SETTINGS_FIXED.md"
  "ADMIN_FINANCIAL_SETTINGS_MINIMAL_DESIGN.md"
  "ADMIN_FINANCIAL_SETTINGS_QUICK_WINS_COMPLETE.md"
  "ADMIN_FINANCIAL_SETTINGS_READY.md"
  "ADMIN_FINANCIAL_SETTINGS_REFACTORED.md"
  "ADMIN_FINANCIAL_SETTINGS_UX_FIXED.md"
  "ADMIN_FINANCIAL_SETTINGS_UX_REDESIGN.md"
  "ADMIN_FINANCIAL_SETTINGS_WARNINGS_FIXED.md"
  
  # Admin Providers
  "ABSOLUTE_FINAL_FIX.md"
  "ULTIMATE_INLINE_FIX.md"
  "FINAL_FIX_WITH_LOGGING.md"
  "FINAL_FIX_FUNCTION_APPROACH.md"
  "PRODUCTION_INTENSIVE_FIX.md"
  "PROFESSIONAL_FIX_COMPLETE.md"
  "ADMIN_PROVIDERS_STATUS_DROPDOWN.md"
  "ADMIN_PROVIDERS_STATUS_DROPDOWN_FIXED.md"
  "ADMIN_PROVIDERS_STATUS_DROPDOWN_COMPLETE.md"
  "ADMIN_PROVIDERS_STATUS_DROPDOWN_PRODUCTION_FIX.md"
  
  # Admin Topup
  "ADMIN_TOPUP_INTERFACE_TYPE_FIX_2026-01-28.md"
  "ADMIN_TOPUP_NULL_PHONE_FIX_2026-01-28.md"
  "ADMIN_TOPUP_REQUESTED_AT_NULL_FIX_2026-01-28.md"
  "ADMIN_TOPUP_TRACKING_ID_RPC_FIX_2026-01-28.md"
  "ADMIN_TOPUP_MISSING_RECORD_DIAGNOSIS_2026-01-28.md"
  "ADMIN_TOPUP_HARD_REFRESH_GUIDE_TH.md"
  
  # Queue Booking
  "QUEUE_BOOKING_BALANCE_MISMATCH_DEBUG.md"
  "QUEUE_BOOKING_WALLET_BALANCE_DEBUG_FIX.md"
  "QUEUE_BOOKING_ZERO_BALANCE_FIX.md"
  "QUEUE_BOOKING_WALLET_DIAGNOSTIC.md"
  "QUEUE_BOOKING_WALLET_FINAL_FIX.md"
  "QUEUE_BOOKING_WALLET_MCP_DIAGNOSIS.md"
  "QUEUE_BOOKING_WALLET_ZERO_DIAGNOSIS_FINAL.md"
  "QUEUE_BOOKING_WALLET_REACTIVITY_FIX_2026-01-26.md"
  "QUEUE_BOOKING_WALLET_BALANCE_DISPLAY_2026-01-26.md"
  "QUEUE_BOOKING_DESIGN_COMPARISON.md"
  "QUEUE_BOOKING_IMPACT_ANALYSIS.md"
  "QUEUE_BOOKING_CONFIRMED_AT_IMPACT_ANALYSIS.md"
  
  # Shopping Chat
  "SHOPPING_CHAT_CHECK_CONSTRAINT_FIX_2026-01-27.md"
  "SHOPPING_CHAT_BROWSER_REFRESH_REQUIRED.md"
  "SHOPPING_CHAT_COMPLETE_FIX_2026-01-27.md"
  "SHOPPING_CHAT_RPC_FUNCTIONS_FIXED_2026-01-27.md"
  "SHOPPING_CHAT_ALL_FIXES_COMPLETE_2026-01-27.md"
  "SHOPPING_CHAT_RPC_400_ERROR_FIXED_2026-01-27.md"
  "SHOPPING_CHAT_HARD_REFRESH_REQUIRED_TH.md"
  "SHOPPING_CHAT_FINAL_FIX_SUMMARY_2026-01-27.md"
  "SHOPPING_CHAT_PARAMETER_NAME_FIX_2026-01-27.md"
  "SHOPPING_CHAT_TYPE_MISMATCH_ENGINEERING_ANALYSIS_2026-01-27.md"
  "SHOPPING_CHAT_TYPE_MISMATCH_FIXED_2026-01-27.md"
  "SHOPPING_CHAT_FIX_QUICK_GUIDE_TH.md"
  
  # Shopping Wallet
  "SHOPPING_WALLET_BALANCE_FIX_2026-01-28.md"
  "SHOPPING_WALLET_BALANCE_UI_FIX_2026-01-28.md"
  "SHOPPING_WALLET_BALANCE_ENHANCEMENTS_2026-01-28.md"
  "SHOPPING_WALLET_DUAL_SYSTEM_FIX_2026-01-28.md"
  "SHOPPING_WALLET_FIX_TEST_GUIDE_TH.md"
  "SHOPPING_WALLET_ENGINEERING_FIX_2026-01-28.md"
  "SHOPPING_WALLET_COMPLETE_ENGINEERING_AUDIT_2026-01-28.md"
  
  # Provider
  "PROVIDER_HOME_SHOPPING_DEBUG_2026-01-27.md"
  "PROVIDER_HOME_SHOPPING_VISIBILITY_FIX_2026-01-27.md"
  "PROVIDER_HOME_NO_ORDERS_DEBUG_2026-01-27.md"
  "PROVIDER_HOME_BROWSER_CACHE_SOLUTION_2026-01-27.md"
  "PROVIDER_SHOPPING_ACCEPT_RLS_FIX_2026-01-27.md"
  "PROVIDER_SHOPPING_ACCEPT_TEST_INSTRUCTIONS_TH.md"
  "PROVIDER_SHOPPING_ACCEPT_BROWSER_CACHE_FIX_2026-01-27.md"
  "PROVIDER_SHOPPING_JOB_MATCHED_VIEW_FIX_2026-01-27.md"
  "PROVIDER_SHOPPING_MATCHED_VIEW_TEST_GUIDE.md"
  "PROVIDER_QUEUE_BOOKING_DEBUG_2026-01-27.md"
  "PROVIDER_QUEUE_BOOKING_PENDING_STATUS_FIX_2026-01-27.md"
  "PROVIDER_QUEUE_BOOKING_FOREIGN_KEY_FIX_2026-01-27.md"
  "PROVIDER_QUEUE_BOOKING_UPDATE_STATUS_FIX_2026-01-27.md"
  "PROVIDER_QUEUE_BOOKING_ACCEPT_RLS_FIX_2026-01-27.md"
  "PROVIDER_QUEUE_BOOKING_STATUS_UPDATE_FIX_2026-01-27.md"
  "PROVIDER_QUEUE_CONFIRMED_STATUS_FIX_2026-01-27.md"
  
  # Tracking
  "TRACKING_CANCEL_FUNCTION_FIXED.md"
  "TRACKING_PAGE_COMPLETE_FIX.md"
  "TRACKING_PAGE_CSS_FIXED.md"
  "TRACKING_CSS_DEEP_ANALYSIS.md"
  "TRACKING_SHOPPING_CHAT_COMPUTED_REF_FIX_2026-01-27.md"
  "TRACKING_SHOPPING_ITEMS_DISPLAY_2026-01-27.md"
  "TRACKING_SHOPPING_ORDER_UI_COMPLETE_2026-01-27.md"
  "TRACKING_PROVIDER_ACCESS_COMPLETE_2026-01-27.md"
  
  # Cache/Browser
  "BROWSER_REFRESH_REQUIRED.md"
  "HARD_REFRESH_GUIDE.md"
  "CACHE_BUSTING_GUIDE.md"
  "CACHE_CLEARED_NEXT_STEPS.md"
  "CLEAR_CACHE_INSTRUCTIONS.md"
  "QUEUE_BOOKING_BROWSER_CACHE_CRITICAL_2026-01-27.md"
  "SHOPPING_TRACKING_CANCEL_BROWSER_CACHE_FIX_2026-01-27.md"
  "PROVIDER_HARD_REFRESH_INSTRUCTIONS_TH.md"
  
  # Deployment
  "DEPLOYMENT_COMPLETE.md"
  "COMMIT_AND_DEPLOY.md"
  "DEPLOYMENT_GUIDE.md"
  
  # Analysis/Debug
  "MAP_DEEP_ANALYSIS.md"
  "SHOPPING_FEATURE_DEEP_ANALYSIS.md"
  "SHOPPING_DATA_QUALITY_CRISIS_2026-01-27.md"
  "SHOPPING_SERVICE_FEE_ZERO_BUG_2026-01-27.md"
  "SHP-20260127-350085_ROLE_BASED_ANALYSIS_2026-01-27.md"
  "TYPESCRIPT_ERRORS_ANALYSIS_2026-01-28.md"
  "QUEUE_BOOKING_STATUS_UPDATE_DEEP_ANALYSIS_2026-01-27.md"
  
  # Misc
  "CURRENT_WORK_STATUS.md"
  "STATUS_CHANGE_FLOW.md"
  "MIGRATION_GUIDE.md"
  "PERFORMANCE_OPTIMIZATION_COMPLETE.md"
  "LINT_FIXES_COMPLETE.md"
  "ADMIN_SETUP_COMPLETE.md"
)

# Move files to archive
moved=0
not_found=0

for file in "${OBSOLETE_FILES[@]}"; do
  if [ -f "$file" ]; then
    mv "$file" "$ARCHIVE_DIR/"
    echo "✅ Archived: $file"
    ((moved++))
  else
    ((not_found++))
  fi
done

echo ""
echo "📊 Summary:"
echo "  ✅ Files archived: $moved"
echo "  ⚠️  Files not found: $not_found"
echo "  📁 Archive location: $ARCHIVE_DIR"
echo ""
echo "✨ Cleanup complete!"
